apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: journey
  namespace: tsm
  annotations:
    texas.nais.io/enabled: "true"

spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 280m
      memory: 830Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: dokarkiv.prod-fss-pub.nais.io
  envFrom:
    - secret: sykmelding-bucket
  env:
    - name: DOKARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOKARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
