ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

app {
  name = journey-local
  runtime = local
}

tsm {
  bucket = fake-bucket
}

kafka {
  config {
    "bootstrap.servers" = "localhost:9092"
    "bootstrap.servers" = ${?BOOTSTRAP_SERVERS}
    "security.protocol" = "PLAINTEXT"
  }
  sykmeldingConsumer {
    longPoll: PT10S
  }
}
