ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

app {
  name = journey-local
  runtime = local
}

tsm {
  bucket = fake-bucket
}

kafka {
  sykmeldingConsumer {
    longPoll: PT10S
    retryDelay: PT10S
  }
}
