ktor {
  deployment {
    port = 8080
    port = ${?PORT}
    # Allow long-poll to finish before shutting down
    shutdownTimeout: 20000
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

app {
  name = ${NAIS_POD_NAME}
}

external {
  dokarkiv = ${DOKARKIV_URL}
}

tsm {
  bucket = ${TSM_SYKMELDING_BUCKET}
}

kafka {
  sykmeldingConsumer {
    longPoll: PT10S
    retryDelay: PT60S
  }
}
